# Generated by Django 2.1.2 on 2018-10-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='contest_done',
            new_name='round1_done',
        ),
        migrations.AddField(
            model_name='team',
            name='round2_done',
            field=models.BooleanField(default=False),
        ),
    ]
