# Generated by Django 2.1.2 on 2018-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20181026_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gate_set',
            field=models.IntegerField(default=-1),
        ),
    ]
