# Generated by Django 2.1.2 on 2018-10-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20181014_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='point',
            new_name='score',
        ),
    ]
