# Generated by Django 2.1.2 on 2018-10-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_team_contest_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='phase1_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
